services:
  postgres:
    container_name: fleet-postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fleetapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres